/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cylinder */

#ifndef _Included_Cylinder
#define _Included_Cylinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cylinder
 * Method:    calcSurfaceArea
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Cylinder_calcSurfaceArea
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Cylinder
 * Method:    calcVol
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Cylinder_calcVol
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
